services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "Zuzzyyuu"
      PASSWORD: "VlqL123"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "500G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8080:8080/tcp
      - 8080:8080/udp
      require("http").createServer((_, res) => res.end("putz!")).listen(8080)
