services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: "putzgnz"
      PASSWORD: "persib1933"
      RAM_SIZE: "3G"
      CPU_CORES: "2"
      DISK_SIZE: "500G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8080:8080/tcp
      - 8080:8080/udp
